### ISSUE TITLE
What is the recommended hardware for evaluation?

### ISSUE THREAD

**Issue by djm1176** [sp-uhh/sgmse#14]
I am running out of GPU memory (8 GB). How much GPU memory is needed to run the model for evaluation?

**Comment by julius-richter** [comment]
When I run the evaluation script on my GPU it uses 6378 MB of memory. Maybe there are other processes running on your GPU at the same time, because it should actually be possible to run the script with 8 GB of GPU memory.

**Comment by szh404** [comment]
> I am running out of GPU memory (8 GB). How much GPU memory is needed to run the model for evaluation?

can you run evaluation successfully? If you run the command that [python enhancement.py ...]
