### ISSUE TITLE
Missing file: fused.so

### ISSUE THREAD

**Issue by PengyvWANG** [sp-uhh/sgmse#27]
Hi, I tried to run your code. After running train.py there is an error
`ImportError: /mnt/inspurfs/home/wangpengyu/.cache/torch_extensions/py38_cu102/fused/fused.so: cannot open shared object file: No such file or directory`
Seems lake some files are missing. Where can I find it? I just install the packages in requirement.txt
Really need your help

**Comment by HULULUUUU** [comment]
Hi, have you finally solved this problem?

**Comment by HULULUUUU** [comment]
Ok, I found a different solution, open fused sitting in the folder, modify the contents of the build.ninja file, change the ninja version and nvcc to the correct location and run the ninja command to generate. Thank u for your reply.



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 10, 2024 15:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sp-uhh/sgmse] Missing file: fused.so (Issue #27)




  
Hi, have you finally solved this problem?
  
Yes, I built my environment from scratch and checked my CUDA settings.
