### ISSUE TITLE
Try to run on CPU

### ISSUE THREAD

**Issue by SediRzm** [sp-uhh/sgmse#28]
Hi, I have tried to run the model (just run) using CPU, instead of Cuda. I have changed all places the .cuda to .cpu and set the device to cpu as well. I face the IndexError: list index out of range. Do you have any suggestion? I have run it before on GPU on another system. I need to change to CPU now. Do you have any solution?

**Comment by julius-richter** [comment]
I the latest commit, I have added the argument  `--device` to `enhancement.py`. You can now run the enhancement on CPU with `--device cpu`.
