### ISSUE TITLE
Dereverberation not work

### ISSUE THREAD

**Issue by loboere** [sp-uhh/sgmse#3]
I run
`!python enhancement.py   --test_dir "/content/test" --enhanced_dir "/content/na"   --ckpt "/content/drive/MyDrive/SGMSE+ Dereverberation Checkpoints/epoch=326-step=408750.ckpt"`

but the results are not the same as in the demo page ,the sound comes out saturated

**Comment by cobalamin** [comment]
Hi, sorry about this. We had accidentally removed some options for the network that we thought were unused. It should be fixed on the most recent commit, https://github.com/sp-uhh/sgmse/commit/c2641a9a0b88341563fa95983e60fe0cf377d795 . I checked both SE and Dereverberation again.

Note that changing the sampler settings slightly seems to work better for dereverberation, using `--N 50 --snr 0.33` (I'll also add this info to the README).

**Comment by cobalamin** [comment]
Closing this now due to inactivity. Feel free to open another issue if something is still broken for you.
