### ISSUE TITLE
The data simulation is not reproducible..

### ISSUE THREAD

**Issue by LiChenda** [sp-uhh/sgmse#35]
Dear authors,

Thank you for open-sourcing this awesome work!
I have run the data simulation script `create_wsj0_reverb.py` on two different servers, but the simulated audio files are different. 
So, how can I make sure that my simulated data is the same as that you used in the paper? `np.random.seed(SEED)` seems to not work as expected. Is it possible to fix the randomness by providing meta files of the intermediate simulation parameters? Or would you like to provide your file list, so I can make sure we are using the same data?

10 audio files (in the test folder) from the first simulation in server 1:
```
anechoic/440c0201_357_2.22_-11.9.wav
anechoic/440c0202_352_1.26_-6.1.wav
anechoic/440c0203_407_1.09_-4.1.wav
anechoic/440c0204_372_0.59_-1.3.wav
anechoic/440c0205_392_0.64_-1.4.wav
anechoic/440c0206_340_1.30_-7.3.wav
anechoic/440c0207_367_1.39_-11.6.wav
anechoic/440c0208_385_1.23_-9.0.wav
anechoic/440c0209_350_1.21_-16.7.wav
```
10 audio files (in the test folder) from the second simulation in server 2:
```
anechoic/440c0201_346_0.40_-9.1.wav
anechoic/440c0202_397_1.52_-15.0.wav
anechoic/440c0203_365_0.88_-12.8.wav
anechoic/440c0204_330_1.73_-12.4.wav
anechoic/440c0205_356_1.60_-9.0.wav
anechoic/440c0206_351_0.65_-8.4.wav
anechoic/440c0207_355_0.62_-10.3.wav
anechoic/440c0208_368_1.33_-12.0.wav
anechoic/440c0209_336_1.79_-17.0.wav
```

**Comment by jmlemercier** [comment]
Hi @LiChenda. `np.random.seed()` works as expected, it is just that we forgot to sort the wsj0 files when fetching them with `glob()`, hence the difference order on different machines. Just pushed a change with `sorted(glob(...))` which fixes the behaviour.

**Comment by LiChenda** [comment]
Thank you @jmlemercier !
