### ISSUE TITLE
Training loss

### ISSUE THREAD

**Issue by yangdongchao** [sp-uhh/sgmse#39]
Great work! Can you share the training loss logging? I am trying to reproduce it, but I find the training loss is very large: loss=1.64e+03. It is normal? I training 20 epoch, but find it does not work now.

**Comment by julius-richter** [comment]
This is what typical loss curves look like:

![loss_curves](https://github.com/sp-uhh/sgmse/assets/46594430/4bd04609-b3a2-4fac-a582-a27e24f2653d)
