### ISSUE TITLE
The enhanced.py can't generate the enhanced.wav

### ISSUE THREAD

**Issue by Lieber0402** [sp-uhh/sgmse#45]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [26:19<00:00, 526.42s/it] 

While this is showing in the terminal, nothing genertated in the target directory.

This is the command to excute the enhanced.py:
python enhancement.py --test_dir D:\Desktop\11\train  --enhanced_dir D:\Desktop\processed\denoise  --ckpt D:\Desktop\pre_trained\denoise\train_vb_29nqe0uh_epoch=115.ckpt

Nothing was generated in the --enhanced_dir.

**Comment by PavelPanjaya** [comment]
Same here. 

Their code assumes there is a `noisy` directory inside your test directory:

```
noisy_dir = join(args.test_dir, 'noisy/')
```

**Comment by Benedict-Cumberbatch-001** [comment]
> Hi there,
> 
> I have updated `enhancement.py`. Now `--test_dir` should point to the directory containing the test data (without assuming a `noisy` directory inside). `--enhanced_dir` is the directory where the enhanced files will be saved.

It still doesn't work. I used the 00000_-1.9dB.wav file in the [example](https://github.com/sp-uhh/gen-se-demo/), but neither created a new enhanced_dir nor output a file. 
I modified the logic for saving the file, but found that the generated file was not denoised. It seems that this file did not call **model.enhance()**?Is it included in the **get_xx_sampler()**?
