### ISSUE TITLE
Wrong output shape in enhancement.py

### ISSUE THREAD

**Issue by PavelPanjaya** [sp-uhh/sgmse#47]
The shape of the output tensor `x_hat` is `torch.Size([2, 758949])` which can't be written as audio file because of the first dimension.

**Comment by cobalamin** [comment]
The model is designed for single-channel speech enhancement; you may be providing a stereo input file?

**Comment by PavelPanjaya** [comment]
Thanks for your response,
I've converted my audio to mono and it works now.
Thanks.

**Comment by cobalamin** [comment]
Great! Closing this issue.
