### ISSUE TITLE
Duplicate: parser.add_argument("--attn_resolutions", type=int, nargs='+', default=[])

### ISSUE THREAD

**Issue by turian** [sp-uhh/sgmse#49]
In ncsnpp_48k.py code, --attn_resolutions is added twice to the argument parser:

```
parser.add_argument("--attn_resolutions", type=int, nargs='+', default=[])
```

This causes an issue trying to train with this backbone.

**Comment by julius-richter** [comment]
Thanks. Just fixed the bug.

**Comment by julius-richter** [comment]
Please pull again. Just made some important changes.

**Comment by turian** [comment]
@julius-richter Thank you
