### ISSUE TITLE
White noise for 48kHz model

### ISSUE THREAD

**Issue by isomov** [sp-uhh/sgmse#50]
Hello, thanks for the great work and 48kHz checkpoint! I was trying to check it on my 48kHz audio, however it produces white noise. I did not change code and installed my environment using requirements_version.txt. This is how I run the model:
"python enhancement.py --test_dir noisy48/ --enhanced_dir enhanced/ --ckpt EARS\ checkpoints/ears_wham.ckpt"
Can you help me with that, please?

**Comment by julius-richter** [comment]
I just checked again, and it works on my side. 

Have you pulled the latest commit?

Can you show me the data that you want to enhance?
