### ISSUE TITLE
enhancement.py error

### ISSUE THREAD

**Issue by musend** [sp-uhh/sgmse#52]
the error is this line y = resample(y, orig_sr=sr, target_sr=target_sr)
![image](https://github.com/user-attachments/assets/960772ea-9d86-4389-b102-821521dfe699)
but when i change it to y = torchaudio.transforms.Resample(orig_freq=sr, new_freq=target_sr)(y) 
the other error appears 

Traceback (most recent call last):
  File "/data/lh/sgmse/enhancement.py", line 78, in <module>
    sample, _ = sampler()
    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 15.42 GiB. GPU 0 has a total capacity of 79.10 GiB of which 6.18 GiB is free. Process 2593452 has 72.91 GiB memory in use. Of the allocated memory 55.95 GiB is allocated by PyTorch, and 15.84 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
    
    
    
   But my H100 80G is completely unoccupied and empty

**Comment by julius-richter** [comment]
It should be fixed in the latest commit.
