### ISSUE TITLE
what is the test dir?

### ISSUE THREAD

**Issue by FrankCasbert** [sp-uhh/sgmse#54]
`python calc_metrics.py --test_dir <your_test_dir> --enhanced_dir <your_enhanced_dir>`

The calc_metrics.py needs three directories: clean dir, noisy dir and enhanced dir. However, the guideline say `--test_dir <your_test_dir>`

So how to enter my file, I'm confused. Should I enter 'python calc_metrics.py --clean_dir test/clean --noisy_dir test/noisy_dir ...'

thanks

**Comment by grepLord** [comment]
yes I had the same query. I also tried the modified command. It worked. 

I have some doubt regarding the enhanced files. Why is their two folders inside enhanced dir. one is clean and other is noisy. Is it not supposed to generate just an enhanced output from the given clean and noisy input files. 

Kindly respond at the earliest.

Thanks.

**Comment by julius-richter** [comment]
What do you mean by "Why is there two folders inside enhanced dir"?

**Comment by grepLord** [comment]
Thanks for the reply.

What I mean is that, when noisy files and clean files are given as tests cases to the model, it is supposed to generate enhanced speech files. Now it does generates them but along with it, it also has noisy dir in the enhancement dir. So I have clean dir and noisy dir inside the enhancement dir. Is this correct?

**Comment by julius-richter** [comment]
The clean files are not given to the model for enhancement (see enhancement.py https://github.com/sp-uhh/sgmse/blob/main/enhancement.py#L38).

The clean files are only used to calculate the intrusive speech metrics (see calc_metrics.py https://github.com/sp-uhh/sgmse/blob/main/calc_metrics.py).

Enhancement dir contains the enhanced files only.

Does that make sense?
