### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by snufas** [sp-uhh/sgmse#6]
not sure what the problem is...

(sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse# python enhancement.py --test_dir input --enhanced_dir output --ckpt models/Speech_Enhancement/train_wsj0_2cta4cov_epoch=159.ckpt
Traceback (most recent call last):
  File "enhancement.py", line 10, in <module>
    from sgmse.model import ScoreModel
  File "/home/snufas/github_projects/sgmse/sgmse/model.py", line 11, in <module>
    from sgmse.backbones import BackboneRegistry
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/__init__.py", line 2, in <module>
    from .ncsnpp import NCSNpp
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp.py", line 18, in <module>
    from .ncsnpp_utils import layers, layerspp, normalization
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/layerspp.py", line 20, in <module>
    from . import up_or_down_sampling
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/up_or_down_sampling.py", line 10, in <module>
    from .op import upfirdn2d
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1514, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1622, in _prepare_ldflags
    extra_ldflags.append(f'-L{_join_cuda_home("lib64")}')
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2125, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
(sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse#

Thanks for help......

**Comment by snufas** [comment]
I managed to get rit of the error above how ever another popped up 

(sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse# python enhancement.py --test_dir input --enhanced_dir output/ --ckpt models/Speech_Enhancement/train_wsj0_2cta4cov_epoch=159.ckpt
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "enhancement.py", line 10, in <module>
    from sgmse.model import ScoreModel
  File "/home/snufas/github_projects/sgmse/sgmse/model.py", line 11, in <module>
    from sgmse.backbones import BackboneRegistry
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/__init__.py", line 2, in <module>
    from .ncsnpp import NCSNpp
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp.py", line 18, in <module>
    from .ncsnpp_utils import layers, layerspp, normalization
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/layerspp.py", line 20, in <module>
    from . import up_or_down_sampling
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/up_or_down_sampling.py", line 10, in <module>
    from .op import upfirdn2d
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /usr/local/cuda-11.7/bin/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/bin/include -isystem /root/miniconda3/envs/sgmse/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_52,code=sm_52 --compiler-options '-fPIC' -std=c++14 -c /home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
FAILED: fused_bias_act_kernel.cuda.o
/usr/local/cuda-11.7/bin/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/bin/include -isystem /root/miniconda3/envs/sgmse/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_52,code=sm_52 --compiler-options '-fPIC' -std=c++14 -c /home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
/bin/sh: 1: /usr/local/cuda-11.7/bin/bin/nvcc: not found
ninja: build stopped: subcommand failed.

(sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse#

**Comment by cobalamin** [comment]
> ` /bin/sh: 1: /usr/local/cuda-11.7/bin/bin/nvcc: not found`

Some path seems to be set up wrong here (there's a duplicate `bin`: `.../bin/bin/...`). Could you maybe look back into how you fixed the missing CUDA_HOME problem, and check if there's an extra `bin` that shouldn't be there?

**Comment by snufas** [comment]
@cobalamin 
now i am geting no errors, but no output eather...
![image](https://user-images.githubusercontent.com/14276936/189369543-d458e538-af0a-4264-958d-b6ca939a450c.png)

**Comment by cobalamin** [comment]
It seems the script didn't find any files. Does your `test_dir` match the required structure, in particular are the `.wav` files stored in a subdirectory named `noisy/`? (see `python enhancement.py --help`).

**Comment by julius-richter** [comment]
Please create another folder named "noisy" inside your folder named "input" and put the files to be processed there. Then the call `python enhancement.py --test_dir input --enhanced_dir output --ckpt models/Speech_Enhancement/train_wsj0_2cta4cov_epoch=159.ckpt` should work. 

See: https://github.com/sp-uhh/sgmse/blob/cfe2704ee22339e400fb83512924e7fb69eaec53/enhancement.py#L24

**Comment by snufas** [comment]
@julius-richter 
Have no ideas what to do with this:

root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse# conda activate sgmse
(sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse# python enhancement.py --test_dir input --enhanced_dir output --ckpt models/Speech_Enhancement/train_wsj0_2cta4cov_epoch=159.ckpt
  0%|                                                                                             | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "enhancement.py", line 63, in <module>
    sample, _ = sampler()
  File "/home/snufas/github_projects/sgmse/sgmse/sampling/__init__.py", line 60, in pc_sampler
    xt, xt_mean = corrector.update_fn(xt, vec_t, y)
  File "/home/snufas/github_projects/sgmse/sgmse/sampling/correctors.py", line 77, in update_fn
    grad = self.score_fn(x, t, *args)
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/snufas/github_projects/sgmse/sgmse/model.py", line 142, in forward
    score = -self.dnn(dnn_input, t)
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp.py", line 304, in forward
    h = modules[m_idx](hs[-1], temb)
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/layerspp.py", line 243, in forward
    h = self.act(self.GroupNorm_0(x))
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 391, in forward
    return F.silu(input, inplace=self.inplace)
  File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/nn/functional.py", line 2048, in silu
    return torch._C._nn.silu(input)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
(sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse#

any suggestions????
Thanks for your input...

**Comment by cobalamin** [comment]
@snufas This does not look like a problem with our code since it errors deep within the implementation of PyTorch. I sometimes have errors like that occur on my machine when I wake it up from sleep mode. Have you tried restarting your machine, to force the CUDA kernel modules to reinitialize?

If you have restarted your machine and it doesn't help, can you try calling the following, as the error message suggests:
```
CUDA_LAUNCH_BLOCKING=1 python enhancement.py --test_dir input --enhanced_dir output --ckpt models/Speech_Enhancement/train_wsj0_2cta4cov_epoch=159.ckpt
```
and see if you get some additional debugging output?

**Comment by snufas** [comment]
@cobalamin 
Nothing,  "CUDA_LAUNCH_BLOCKING=1"  didn't give any extra information.
I didn't have problems like this in any other project, I am not saying that it is a project's fault, may be due to the specific configuration.
3 things to note though
1 I am running on wsl2 
2 my GPU is quite old NVIDIA GeForce GTX 980
3 also I am still not able to get the cuda home path for some reason.

So yeah, I doubt that I will be able to run this project...
But thank you very much for your input and suggestions, I really appreciate that.
Feel free to close this issue yourself, I giving up on it, although samples  sounds very good indeed.

**Comment by osimantir** [comment]
> not sure what the problem is...
> 
> (sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse# python enhancement.py --test_dir input --enhanced_dir output --ckpt models/Speech_Enhancement/train_wsj0_2cta4cov_epoch=159.ckpt Traceback (most recent call last): File "enhancement.py", line 10, in from sgmse.model import ScoreModel File "/home/snufas/github_projects/sgmse/sgmse/model.py", line 11, in from sgmse.backbones import BackboneRegistry File "/home/snufas/github_projects/sgmse/sgmse/backbones/**init**.py", line 2, in from .ncsnpp import NCSNpp File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp.py", line 18, in from .ncsnpp_utils import layers, layerspp, normalization File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/layerspp.py", line 20, in from . import up_or_down_sampling File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/up_or_down_sampling.py", line 10, in from .op import upfirdn2d File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/**init**.py", line 1, in from .fused_act import FusedLeakyReLU, fused_leaky_relu File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/fused_act.py", line 11, in fused = load( File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1202, in load return _jit_compile( File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile _write_ninja_file_and_build_library( File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1514, in _write_ninja_file_and_build_library extra_ldflags = _prepare_ldflags( File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1622, in _prepare_ldflags extra_ldflags.append(f'-L{_join_cuda_home("lib64")}') File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2125, in _join_cuda_home raise EnvironmentError('CUDA_HOME environment variable is not set. ' OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root. (sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse#
> 
> Thanks for help......

Hi! I'm getting the same error. How did you solve it? Thank you.

**Comment by tvanh512** [comment]
"OSError: CUDA_HOME environment variable is not set" could be solved with "conda install -c conda-forge cudatoolkit-dev"

**Comment by raimmm** [comment]
> I managed to get rit of the error above how ever another popped up
> 
> (sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse# python enhancement.py --test_dir input --enhanced_dir output/ --ckpt models/Speech_Enhancement/train_wsj0_2cta4cov_epoch=159.ckpt Traceback (most recent call last): File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build subprocess.run( File "/root/miniconda3/envs/sgmse/lib/python3.8/subprocess.py", line 516, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "enhancement.py", line 10, in from sgmse.model import ScoreModel File "/home/snufas/github_projects/sgmse/sgmse/model.py", line 11, in from sgmse.backbones import BackboneRegistry File "/home/snufas/github_projects/sgmse/sgmse/backbones/**init**.py", line 2, in from .ncsnpp import NCSNpp File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp.py", line 18, in from .ncsnpp_utils import layers, layerspp, normalization File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/layerspp.py", line 20, in from . import up_or_down_sampling File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/up_or_down_sampling.py", line 10, in from .op import upfirdn2d File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/**init**.py", line 1, in from .fused_act import FusedLeakyReLU, fused_leaky_relu File "/home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/fused_act.py", line 11, in fused = load( File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1202, in load return _jit_compile( File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile _write_ninja_file_and_build_library( File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1537, in _write_ninja_file_and_build_library _run_ninja_build( File "/root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error building extension 'fused': [1/2] /usr/local/cuda-11.7/bin/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/bin/include -isystem /root/miniconda3/envs/sgmse/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_52,code=sm_52 --compiler-options '-fPIC' -std=c++14 -c /home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o FAILED: fused_bias_act_kernel.cuda.o /usr/local/cuda-11.7/bin/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/sgmse/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/bin/include -isystem /root/miniconda3/envs/sgmse/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_52,code=sm_52 --compiler-options '-fPIC' -std=c++14 -c /home/snufas/github_projects/sgmse/sgmse/backbones/ncsnpp_utils/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o /bin/sh: 1: /usr/local/cuda-11.7/bin/bin/nvcc: not found ninja: build stopped: subcommand failed.
> 
> (sgmse) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/sgmse#

Excuse me, how did you solve this problem

**Comment by a897456** [comment]
Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\utils\cpp_extension.py", line 2096, in _run_ninja_build
    subprocess.run(
  File "E:\ProgramData\anaconda3\envs\py39sgmse\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\000\sgmse-main\sgmse\backbones\__init__.py", line 2, in <module>
    from .ncsnpp import NCSNpp
  File "E:\000\sgmse-main\sgmse\backbones\ncsnpp.py", line 18, in <module>
    from .ncsnpp_utils import layers, layerspp, normalization
  File "E:\000\sgmse-main\sgmse\backbones\ncsnpp_utils\layerspp.py", line 20, in <module>
    from . import up_or_down_sampling
  File "E:\000\sgmse-main\sgmse\backbones\ncsnpp_utils\up_or_down_sampling.py", line 10, in <module>
    from .op import upfirdn2d
  File "E:\000\sgmse-main\sgmse\backbones\ncsnpp_utils\op\__init__.py", line 1, in <module>
    from .upfirdn2d import upfirdn2d
  File "E:\000\sgmse-main\sgmse\backbones\ncsnpp_utils\op\upfirdn2d.py", line 12, in <module>
    upfirdn2d_op = load(
  File "E:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "E:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "E:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\utils\cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'upfirdn2d': [1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output upfirdn2d_kernel.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=upfirdn2d -DTORCH_API_INCLUDE_EXTENSION_H -IE:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\include -IE:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\include\torch\csrc\api\include -IE:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\include\TH -IE:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\ProgramData\anaconda3\envs\py39sgmse\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=sm_89 -std=c++17 -c E:\000\sgmse-main\sgmse\backbones\ncsnpp_utils\op\upfirdn2d_kernel.cu -o upfirdn2d_kernel.cuda.o 
FAILED: upfirdn2d_kernel.cuda.o 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output upfirdn2d_kernel.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=upfirdn2d -DTORCH_API_INCLUDE_EXTENSION_H -IE:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\include -IE:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\include\torch\csrc\api\include -IE:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\include\TH -IE:\ProgramData\anaconda3\envs\py39sgmse\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\ProgramData\anaconda3\envs\py39sgmse\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=sm_89 -std=c++17 -c E:\000\sgmse-main\sgmse\backbones\ncsnpp_utils\op\upfirdn2d_kernel.cu -o upfirdn2d_kernel.cuda.o 

ninja: build stopped: subcommand failed.

**Comment by julius-richter** [comment]
Using ChatGPT:

The error message you're encountering indicates that there's a problem with building the `upfirdn2d` extension for PyTorch using NVIDIA's CUDA toolkit and `ninja` build system. Here are some steps and suggestions to help you troubleshoot and resolve this issue:

1. Check CUDA and PyTorch Compatibility:
   - Ensure that the CUDA version installed on your system is compatible with the version of PyTorch you are using. You can check the compatibility matrix on the [PyTorch site](https://pytorch.org/get-started/previous-versions/). For instance, PyTorch 1.12.0 requires at least CUDA 11.3, while you're using CUDA 12.1.

2. NVIDIA Drivers:
   - Ensure that your NVIDIA GPU drivers are up to date and compatible with the installed CUDA version. You can check the driver version using `nvidia-smi` and compare it with the supported versions on NVIDIA's website.

3. Environment Path:
   - Make sure that the CUDA 12.1 bin directory (`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin`) is correctly included in your system's PATH variable. This ensures that `nvcc` is accessible.

4. Ninja Installation:
   - Verify that `ninja` is correctly installed and available in your environment. You can test this by running `ninja --version` from your command line. If not installed, you can install it via `pip`:

        
bash
        pip install ninja
        


5. Reinstall PyTorch and CUDA Toolkit:
   - If any installation issue is suspected, consider reinstalling PyTorch and the CUDA toolkit. Ensure to follow the correct installation instructions for your operating system and hardware configuration.

6. Custom Compiler Flags:
   - Check if any specific custom compiler flags are needed for the CUDA source files you are trying to compile. These flags can sometimes cause conflicts if not set appropriately.
   
7. Dependency Issues:
   - Make sure all dependencies and related packages required by your setup (as mentioned in your error traceback) are correctly installed and up-to-date. This includes ensuring headers and necessary library links are found during the compilation.

8. Debugging Compiler Errors:
   - Sometimes, examining the specific compiler errors can give more insights. Look for any additional logs or error messages provided by `nvcc` while compiling `upfirdn2d_kernel.cu`.

9. Contact or Check Issues from Developers:
   - If you are using a third-party library or a specific repository, check their GitHub issues page to see if others face similar issues. Engaging with maintainers or community forums can sometimes yield quick solutions.

By following these steps, you should be able to locate and resolve the issue that's causing the build failure for the CUDA extension.
