### ISSUE TITLE
数据集，运行

### ISSUE THREAD

**Issue by libai2345** [sp-uhh/sgmse#60]
Very good open source project, where can I download the datasets used in the project? Ask for information

**Comment by julius-richter** [comment]
Thank you. You can download the datasets here:

EARS-WHAM: https://github.com/sp-uhh/ears_benchmark
EARS-Reverb: https://github.com/sp-uhh/ears_benchmark
VoiceBank-Demand: https://datashare.ed.ac.uk/handle/10283/2791
WSJ0: https://catalog.ldc.upenn.edu/LDC93S6A
CHiME3: https://catalog.ldc.upenn.edu/LDC2017S24

**Comment by libai2345** [comment]
Thank you very much for your reply, can the readme of the project be written in more detail, I'm a newbie, and the project hasn't been successful on my computer until now, looking forward to your reply.

**Comment by libai2345** [comment]
Thank you very much for your reply, can the readme of the project be written in more detail, I'm a newbie, and the project hasn't been successful on my computer until now, looking forward to your reply.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sp-uhh/sgmse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月16日(星期六) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sp-uhh/sgmse] 数据集，运行 (Issue #60)





 
Thank you. You can download the datasets here:
 
EARS-WHAM: https://github.com/sp-uhh/ears_benchmark
 EARS-Reverb: https://github.com/sp-uhh/ears_benchmark
 VoiceBank-Demand: https://datashare.ed.ac.uk/handle/10283/2791
 WSJ0: https://catalog.ldc.upenn.edu/LDC93S6A
 CHiME3: https://catalog.ldc.upenn.edu/LDC2017S24
