### ISSUE TITLE
License for code in this repository

### ISSUE THREAD

**Issue by stefan-baumann** [sp-uhh/sgmse#8]
Currently, as far as I can tell, there is no license given for the code in this repository. It would be great if you added one so that people know in which cases they are allowed to use your code and create works based on it.

**Comment by julius-richter** [comment]
Thanks for letting us know. We have now added a MIT licence to the repository. 

As mentioned in the README, we kindly ask you to cite our papers in your publication when using any of our research or code:

```bib
@inproceedings{welker2022speech,
  title={Speech Enhancement with Score-Based Generative Models in the Complex STFT Domain},
  author={Welker, Simon and Richter, Julius and Gerkmann, Timo},
  booktitle={Proc. Interspeech 2022},
  year={2022}
}
```

```bib
@article{richter2022speech,
  title={Speech Enhancement and Dereverberation with Diffusion-based Generative Models},
  author={Richter, Julius and Welker, Simon and Lemercier, Jean-Marie and Lay, Bunlong and Gerkmann, Timo},
  journal={arXiv preprint arXiv:2208.05830},
  year={2022}
}
```

**Comment by stefan-baumann** [comment]
Thank you very much! And I absolutely will, if I'll end up publishing something :)
