### ISSUE TITLE
How to use dereverbration checkpoint for inference? 

### ISSUE THREAD

**Issue by the6thsense** [sp-uhh/sgmse#9]
Please suggest a bash command to run the dereverbration checkpoint.

**Comment by julius-richter** [comment]
That would be

`python enhancement.py --test_dir <your_test_dir> --enhanced_dir <your_enhanced_dir> --ckpt <path_to_model_checkpoint> --N 50 --snr 0.33`

**Comment by the6thsense** [comment]
Thanks @julius-richter, Is it that by just changing the checkpoint file from enhancement one to dereverbration one the model will itself identify which model to load?

**Comment by cobalamin** [comment]
Hi, the only difference between the two models is really the training data (and therefore the weights), as well as some minor changes in the parameterization of the stochastic process. When using `ScoreModel.load_from_checkpoint(...)` as `enhancement.py` does, it will automatically load all of this correctly and be usable for the respective task each model was trained for.

**Comment by the6thsense** [comment]
That sounds interesting. Thanks @cobalamin
